---
- name: Ensure uWSGI directory exists
  file:
    path: "/etc/uwsgi/"
    state: directory
    mode: "0711"
- name: Copy cloudkitty wsgi to apache directory
  template:
    src: cloudkitty-wsgi.py.j2
    dest: "{{ cloudkitty_bin }}/cloudkitty-wsgi.py"
    owner: "{{ cloudkitty_system_user_name }}"
    group: "{{ cloudkitty_system_user_name }}"
    mode: 0755
- name: Apply uWSGI configuration
  config_template:
    src: cloudkitty-uwsgi.ini.j2
    dest: /etc/uwsgi/cloudkitty-api.ini
    mode: 0744
    config_overrides: "{{ cloudkitty_api_uwsgi_overrides }}"
    config_type: ini
  notify:
    - Restart cloudkitty-api